### ISSUE TITLE
今日村中无事

### ISSUE THREAD

**Issue by anonymity12** [bluebird97/zzzfourm#3]
- 今日说说信息输入（news feed == 新闻喂食)

村里今天发生的事情就是这个叫做 *尼古拉斯-赵四* 的老先生讲了讲，如何让村里的信息真实高效：

![D7E9382D2D1F1451E7E3BC6D3618F2E2](https://user-images.githubusercontent.com/14998115/80896737-14787880-8d24-11ea-8366-fde9cb08e13b.jpg)

1. 你要找到权威人士打听消息，不要看电视📺
2. 统计自己的输入 渠道，抛弃那些低质量的新闻来源，比如村头，门口，你要爬过土墙，去东边啦的烽火台。

**Comment by bluebird97** [comment]
http://docs.cooldevelop.com
